version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app/deploy
permissions:
  - object: /home/ec2-user/app/deploy
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
